-- 코드를 입력하세요
/*SELECT 
    CASE WHEN PRODUCT_CODE = 'A1%' THEN 'A1'
         WHEN PRODUCT_CODE = 'A2%' THEN 'A2'
         WHEN PRODUCT_CODE = 'A3%' THEN 'A3'
         WHEN PRODUCT_CODE = 'B1%' THEN 'B1'
         WHEN PRODUCT_CODE = 'B2%' THEN 'B2'
         WHEN PRODUCT_CODE = 'B3%' THEN 'B3'
         WHEN PRODUCT_CODE = 'C1%' THEN 'C1'
         WHEN PRODUCT_CODE = 'C2%' THEN 'C2'
         WHEN PRODUCT_CODE = 'C3%' THEN 'C3'
         WHEN PRODUCT_CODE = 'D1%' THEN 'D1'
         WHEN PRODUCT_CODE = 'D2%' THEN 'D2'
         WHEN PRODUCT_CODE = 'D3%' THEN 'D3'
    END AS CATEGORY, COUNT(PRODUCT_CODE)
FROM PRODUCT
GROUP BY PRODUCT_CODE*/
SELECT SUBSTR(PRODUCT_CODE,0,2) AS CATEGORY, COUNT(*) AS PRODUCT 
FROM PRODUCT 
GROUP BY SUBSTR(PRODUCT_CODE,0,2) 
ORDER BY CATEGORY;